# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Campusgram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Campusgram
   pod 'Parse'
   pod 'AlamofireImage'
   pod  'GoogleMaps', '4.2.0'
   pod  'GooglePlaces', '4.2.0'

  target 'CampusgramTests' do
    inherit! :search_paths
    # Pods for testing
   pod 'Parse'
  end

  target 'CampusgramUITests' do
    inherit! :search_paths
    # Pods for testing
   pod 'Parse'
  end

target 'CampusgramTests' do
    inherit! :search_paths
    # Pods for testing
   pod 'GoogleMaps', '4.2.0'
  end

  target 'CampusgramUITests' do
    inherit! :search_paths
    # Pods for testing
   pod 'GoogleMaps', '4.2.0'
  end
target 'CampusgramTests' do
    inherit! :search_paths
    # Pods for testing
   pod 'GooglePlaces', '4.2.0'
  end

  target 'CampusgramUITests' do
    inherit! :search_paths
    # Pods for testing
   pod 'GooglePlaces', '4.2.0'
  end

end
